### ISSUE TITLE
Does not work with 4.0 kernel serie (upgrading from 3.19.3 fails)

### ISSUE THREAD

**Issue by EricV** [psomas/ketchup#7]
The tricks doen for 232.6 -> 3.0 have to be redone for 3.19.3 -> 4.0.0

**Comment by higuita** [comment]
i'm trying to patch this and is almost working, and until the end of the week i i will probably have this finish. the main problem is the lack of 4.0 directory, we only have 4.x, that breaks the script in several places.

**Comment by higuita** [comment]
pull request created: 
https://github.com/psomas/ketchup/pull/8

If you want to use it now, grab my changed version here: 
https://github.com/higuita/ketchup/blob/experimental/ketchup

**Comment by EricV** [comment]
On 20/04/2015 01:47, higuita wrote:

> pull request created:
> #8 https://github.com/psomas/ketchup/pull/8
> 
> If you want to use it now, grab my changed version here:
> https://github.com/higuita/ketchup/blob/experimental/ketchup
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/psomas/ketchup/issues/7#issuecomment-94325490.

Thanks. I tried but it was not successful

/tmp/ketchup -a /usr/src -G 4.0.0
ketchup: Cannot find patch for 4.0.0
valette@pink-floyd2:/usr/src/linux$ /tmp/ketchup -a /usr/src -G 4.0
3.18.11 -> 4.0
Downloading patch-3.18.11.xz
/home/valette/.ketchup/patch-3.18.11.xz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.bz2
/home/valette/.ketchup/patch-3.18.11.bz2.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11
/home/valette/.ketchup/patch-3.18.11.partial: Aucun fichier ou dossier 
de ce type
Downloading patch-3.18.11.gz
/home/valette/.ketchup/patch-3.18.11.gz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.xz
/home/valette/.ketchup/patch-3.18.11.xz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.bz2
/home/valette/.ketchup/patch-3.18.11.bz2.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11
/home/valette/.ketchup/patch-3.18.11.partial: Aucun fichier ou dossier 
de ce type
Downloading patch-3.18.11.gz
/home/valette/.ketchup/patch-3.18.11.gz.partial: Aucun fichier ou 
dossier de ce type
ketchup: patch download failed

**Comment by higuita** [comment]
For the 4.0.0, that version doesn't really exists, the ftp don't have it, just 4.0. I usually use "ketchup linux" to get the latest version by the way.

For the other error, well, i just tested upgrade from several 3.9.x kernels to 4.0, but there is a bug in the upgrade from 3.18 or below to 4.0  :)
i'm going to check it and update the patch

**Comment by higuita** [comment]
new pull request (https://github.com/psomas/ketchup/pull/9)
The problem was parts of the code still tried to work with bz2 files... but kernel.org stop using that format and converted all to .xz. Should work fine now :)

You can grab a copy of my file from the url above

**Comment by EricV** [comment]
On 21/04/2015 02:29, higuita wrote:

> new pull request (#9 https://github.com/psomas/ketchup/pull/9)
> The problem was parts of the code still tried to work with bz2 files...
> but kernel.org stop using that format and converted all to .xz. Should
> work fine now :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/psomas/ketchup/issues/7#issuecomment-94599344.

This is still not working:

/tmp/ketchup -a /usr/src -G 4.0
3.18.11 -> 4.0
Downloading patch-3.18.11.xz
/home/valette/.ketchup/patch-3.18.11.xz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.bz2
/home/valette/.ketchup/patch-3.18.11.bz2.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11
/home/valette/.ketchup/patch-3.18.11.partial: Aucun fichier ou dossier 
de ce type
Downloading patch-3.18.11.gz
/home/valette/.ketchup/patch-3.18.11.gz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.xz
/home/valette/.ketchup/patch-3.18.11.xz.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11.bz2
/home/valette/.ketchup/patch-3.18.11.bz2.partial: Aucun fichier ou 
dossier de ce type
Downloading patch-3.18.11
/home/valette/.ketchup/patch-3.18.11.partial: Aucun fichier ou dossier 
de ce type
Downloading patch-3.18.11.gz
/home/valette/.ketchup/patch-3.18.11.gz.partial: Aucun fichier ou 
dossier de ce type
ketchup: patch download failed
valette@pink-floyd2:/usr/src/linux-3.15.2$ ls /usr/src/

**Comment by higuita** [comment]
Are you sure you are using my version? The experimental one?  here is my output using my version:

```
# /home/higuita/build/github/ketchup-exp/ketchup -a /usr/src/00/ -G 4.0 
3.18.11 -> 4.0
Applying patch-3.18.11.xz -R
Applying patch-3.19.xz
Applying patch-4.0.xz
```

try to cleanup your /usr/src and /home/valette/.ketchup/ 
I know there is a bug somewhere in the -a option, as it is ignored most of the time... but again with or without that option it works for me. Try to remove the -a option...

I can also work with or without the -G option and also have cleanup my $HOME/.ketchup
So if the cleanup didn't work nor the -a option, i'm out of ideas why is failing to you ...maybe something in your your distro or locale?

**Comment by EricV** [comment]
On 21/04/2015 23:54, higuita wrote:

> Are you sure you are using my version? The experimental one? here is my
> output using my version:
> 
>   /home/higuita/build/github/ketchup-exp/ketchup -a /usr/src/00/ -G 4.0
> 
> 3.18.11 -> 4.0
> Applying patch-3.18.11.xz -R
> Applying patch-3.19.xz
> Applying patch-4.0.xz
> 
> try to cleanup your /usr/src and /home/valette/.ketchup/

I have no .ketchup as a starting point

> I know there is a bug somewhere in the -a option, as it is ignored most
> of the time... but again with or without that option it works for me.
> Try to remove the -a option...

I need that option or need to change multiple scripts

p didn't work nor the -a option, i'm out of ideas why is

> failing to you ...maybe something in your your distro or locale?

The debian ketchup version which is derived from psomas used tow ork up 
until now...

--eric

**Comment by higuita** [comment]
> > try to cleanup your /usr/src and /home/valette/.ketchup/
> I have no .ketchup as a starting point

Then this is your problem... do a `mkdir /home/valette/.ketchup/` and try again.

As the -a option is buggy, is doing the check in the correct folder, but then tries to download using the wrong one. Manually creating the folder should fix the problem.

I will also try to test on my debian box to see if there is any problem with the debian python version

**Comment by EricV** [comment]
On 22/04/2015 23:26, higuita wrote:

> ```
>  > try to cleanup your /usr/src and /home/valette/.ketchup/
> I have no .ketchup as a starting point
> ```
> 
> Then this is your problem... do a |mkdir /home/valette/.ketchup/| and
> try again.

What is supposed to be there and if there is something needed why is it 
not created dynamically?

> As the -a option is buggy, is doing the check in the correct folder, but
> then tries to download using the wrong one. Manually creating the folder
> should fix the problem.

In the debian version, it does it right. And I do not want download to 
go in .ketchup directory but in /usr/src as per the -a option.

> I will also try to test on my debian box to see if there is any problem
> with the debian python version

Please do. There is a working ketchup packages (testing/unstable).

--eric

**Comment by higuita** [comment]
Try to do a  `mkdir /home/valette/.ketchup/` and try again, see if this makes any difference

**Comment by EricV** [comment]
On 04/30/2015 01:05 AM, higuita wrote:

> Try to do a |mkdir /home/valette/.ketchup/| and try again, see if this
> makes any difference
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/psomas/ketchup/issues/7#issuecomment-97610632.

trying 4.0 -> 4.0.1 witha ~/.ketchup directory

/tmp/ketchup -a /usr/src -G 4.0.1
Traceback (most recent call last):
   File "/tmp/ketchup", line 1058, in <module>
     process_args(args)
   File "/tmp/ketchup", line 1038, in process_args
     for v in version_urls(find_ver(args[0])):
   File "/tmp/ketchup", line 486, in version_urls
     'base': base(ver),
   File "/tmp/ketchup", line 225, in base
     v = revbase(ver)
   File "/tmp/ketchup", line 219, in revbase
     if t1 != 1.6 and r == last_minor(t1):
   File "/tmp/ketchup", line 421, in last_minor
     p = map(int, find_www(url, ".*linux-%s.(\d+).tar.(bz2|xz|gz)" % 
t, 1))
   File "/tmp/ketchup", line 380, in find_www
     for l in urllib.urlopen(url).readlines():
   File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
     return opener.open(url)
   File "/usr/lib/python2.7/urllib.py", line 213, in open
     return getattr(self, name)(url)
   File "/usr/lib/python2.7/urllib.py", line 350, in open_http
     h.endheaders(data)
   File "/usr/lib/python2.7/httplib.py", line 1049, in endheaders
     self._send_output(message_body)
   File "/usr/lib/python2.7/httplib.py", line 893, in _send_output
     self.send(msg)
   File "/usr/lib/python2.7/httplib.py", line 855, in send
     self.connect()
   File "/usr/lib/python2.7/httplib.py", line 832, in connect
     self.timeout, self.source_address)
   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
     raise err
IOError: [Errno socket error] [Errno 97] Address family not supported by 
protocol

**Comment by higuita** [comment]
> IOError: [Errno socket error] [Errno 97] Address family not supported by
> protocol

This error is because you have ipv6 and your python install is having problems with it.
you can try to temporarily disable it and see if it works

http://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04

**Comment by EricV** [comment]
On 06/23/2015 02:31 AM, higuita wrote:

> ```
> IOError: [Errno socket error] [Errno 97] Address family not supported by
> protocol
> ```
> 
> This error is because you have ipv6 and your python install is having
> problems with it.

No I do not have IPV6. ANd it is beacuse of that that I have the error.

NB: finally the last version of your scripts works. It is just much 
slower than original.

-- eric

**Comment by fgosew** [comment]
I took the liberty to update the Debian version of this project and updated it to 4.x support. I didn't fork this projects current head because of the substantial differences between this one and Debians version (cloned somewhere in 2011). It does work, but I didn't test all possible settings. Well it's more or less a minor change of the Debian sources, just the copy and paste addition of version 3 to version 4 support with one additional variable, so why shouldn't it? ;)

https://github.com/fgosew/ketchup
